---
- name: Deploiement du serveur MariaDB
  hosts: database
  become: yes
  tasks:
    - name: 1. Mettre a jour la liste des paquets
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 2. Installer le moteur MariaDB
      become: yes
      apt:
        name: mariadb-server
        state: present

    - name: 3. Demarrer le service
      become: yes
      service:
        name: mariadb
        state: started
        enabled: yes
